all:
  children:
    router_ios:
      hosts:
        TPCODL_DC_R1:
    switch_ios:
      hosts:
        TPC_R8_SW_200.6:
    cisco_ios:
      children:
        router_ios:
        switch_ios:
              