all:
  children:
    router_ios:
      hosts:
        TPCODL_DC_R1: {ansible_host: 10.10.0.2} 
    switch_ios:
      hosts:
        TPC_R8_SW_200.6: {ansible_host: 172.20.200.6}  
    nxos:
      hosts:
        TPCODL_DC_Core_1: {ansible_host: 172.20.200.2}       
    cisco_ios:
      children:
        router_ios:
        switch_ios:
              