all:
  children:
    c1100:
      hosts:
        TPCODL_DC_R1: {ansible_host: 10.10.0.2} 
    c2960X:
      hosts:
        TPC_R8_SW_200.6: {ansible_host: 172.20.200.6}  
    nxos:
      hosts:
        TPCODL_DC_Core_1: {ansible_host: 172.20.200.2}
    Cisco: 
      children:
        nxos:          
        cisco_ios:
          children:
            router_ios:
              children:
                c1100:
            switch_ios:
              children:
                c2960X:
                  