---
- name: Upgrade OS of network devices if not compliance.
  hosts: cisco_ios
  gather_facts: true
 
  pre_tasks: 
    - name: Compliance check pre.
      debug:
        msg: "{{ lookup('ansible.builtin.template', 'debug_net_upgrade_os_compliance.j2') }}" 
      tags:
        - compliance

  tasks: 
    - name: UPGRADE OS IMAGE IF NOT COMPLIANT.
      include_role:
        name: upgrade_net_device
      when: ansible_facts.net_version != net_compliant_os.version
