---
# Check if new image already exist and pass checksum.
- name: ENABLE SCP SERVER
  cisco.ios.ios_config:
    lines: 
      - ip scp server enable
      - ip tcp window-size 9999999

- include_tasks: 
    file: cisco_router_isr_md5.yml
    apply:
      tags: verifymd5
  tags: verifymd5

- name: Copy Image // This could take up to 10 minutes
  tags: copyimage
  ansible.netcommon.net_put: 
    src: "files/{{ net_compliant_os.imagename }}"
    dest: "flash:/{{ net_compliant_os.imagename }}"
    protocol: scp
  vars: 
    ansible_command_timeout: 600    


      # vars:
      #   regexp: "{{ net_compliant_os.imagename }}"               

- name: SET BOOT SYSTEM
  tags: bootsystem
  cisco.ios.ios_config:
    before: no boot system
    lines: 
      - boot system flash bootflash:c1100-universalk9_ias.16.10.01b.SPA.bin
    after: config-reg 0x2102

- name: SAVE CONFIG BEFORE RELOAD DEVICE
  tags: reload
  block:
    - name: SAVE CONFIG
      cisco.ios.ios_config:
        save_when: always
    - name: RELOAD DEVICE
      ansible.netcommon.cli_command:
          command: "reload\n"
          sendonly: yes

- name: WAIT FOR DEVICE TO RETURN
  wait_for:
    # host: "{{ inventory_hostname }}"
    # port: 22
    # delay: 180
    timeout: 240
  delegate_to: localhost

## Check current image
- name: GET IOS FACTS AFTER RELOAD
  cisco.ios.ios_facts:
    gather_subset:
      - 'hardware'
    #gather_network_resources: all
    available_network_resources:  no

- debug: 
    msg: 
      - "Current version is {{ ansible_net_version }}"

- name: ASSERT THAT THE IOS VERSION IS CORRECT   
  ansible.builtin.assert:
    success_msg: "Software Upgrade has been completed"
    fail_msg: "Software Upgrade has been failed"
    that:
      - ansible_facts.net_version == net_compliant_os.version
