---
- name: ENABLE SCP SERVER
  cisco.ios.ios_config:
    lines: ip scp server enable
    save_when: changed

# - name: RELOAD DEVICE
#   cli_command:
#     command: reload
#     check_all: yes
#     prompt:
#       - Save\?
#       - confirm
#     answer:
#       - 'y'
#       - "\r"
#   tags:
#     - reload
#   ignore_errors: true

- name: SAVE CONFIG BEFORE RELOAD DEVICE
  block:
    - name: SAVE CONFIG
      cisco.ios.ios_config:
        save_when: always
    - name: RELOAD DEVICE
      ansible.netcommon.cli_command:
          command: "reload\n"
          sendonly: yes

# - name: reset the connection
#   meta: reset_connection

- name: WAIT FOR DEVICE TO RETURN
  wait_for:
    # host: "{{ inventory_hostname }}"
    # port: 22
    # delay: 180
    timeout: 240
  delegate_to: localhost

- name: GET IOS FACTS AFTER RELOAD
  cisco.ios.ios_facts:
    gather_subset:
      - 'hardware'
    #gather_network_resources: all
    available_network_resources:  no
  tags: always
